Repository UCLALibrary/prl-harvester, pull requests merged in 2023-05, with the labels that each got.

#59 [SERV-797] Send configurable User-Agent HTTP header on outgoing requests
  README.md
  src/main/java/edu/ucla/library/prl/harvester/Config.java
  src/main/java/edu/ucla/library/prl/harvester/Constants.java
  src/main/java/edu/ucla/library/prl/harvester/OaipmhUtils.java
  src/main/java/edu/ucla/library/prl/harvester/handlers/AbstractRequestHandler.java
  src/main/java/edu/ucla/library/prl/harvester/handlers/AbstractSolrAwareWriteOperationHandler.java
  src/main/java/edu/ucla/library/prl/harvester/handlers/AddJobsHandler.java
  src/main/java/edu/ucla/library/prl/harvester/handlers/AuthHandler.java
  src/main/java/edu/ucla/library/prl/harvester/handlers/GetInstitutionHandler.java
  src/main/java/edu/ucla/library/prl/harvester/handlers/GetJobHandler.java
  src/main/java/edu/ucla/library/prl/harvester/handlers/ListInstitutionsHandler.java
  src/main/java/edu/ucla/library/prl/harvester/handlers/ListJobsHandler.java
  src/main/java/edu/ucla/library/prl/harvester/handlers/RemoveJobHandler.java
  src/main/java/edu/ucla/library/prl/harvester/handlers/UpdateJobHandler.java
  src/main/java/edu/ucla/library/prl/harvester/services/HarvestServiceImpl.java
  src/main/java/edu/ucla/library/prl/harvester/verticles/MainVerticle.java
  src/test/java/edu/ucla/library/prl/harvester/AuthorizedFIT.java
  src/test/java/edu/ucla/library/prl/harvester/DatabaseIT.java
  src/test/java/edu/ucla/library/prl/harvester/FrontEndIT.java
  src/test/java/edu/ucla/library/prl/harvester/InstitutionRequestsFT.java
  src/test/java/edu/ucla/library/prl/harvester/JobRequestsFT.java
  src/test/java/edu/ucla/library/prl/harvester/LdapAuthIT.java
  src/test/java/edu/ucla/library/prl/harvester/OaipmhUtilsFT.java
  src/test/java/edu/ucla/library/prl/harvester/handlers/StatusHandlerIT.java
  src/test/java/edu/ucla/library/prl/harvester/services/HarvestJobSchedulerServiceIT.java
  src/test/java/edu/ucla/library/prl/harvester/services/HarvestScheduleStoreServiceIT.java
  src/test/java/edu/ucla/library/prl/harvester/services/HarvestServiceIT.java
  src/test/java/edu/ucla/library/prl/harvester/utils/TestUtils.java
Labels: feature

#63 [SERV-812] Ignore empty metadata elements
  src/main/java/edu/ucla/library/prl/harvester/services/HarvestServiceUtils.java
  src/test/resources/provider/set1/zz00253w02.xml
Labels: bugfix

#61 [SERV-595] Update Solr search config
  src/main/resources/solrconfig.xml
Labels: bugfix

#64 [SERV-813] Make OAI-PMH client HTTP timeout configurable
  README.md
  pom.xml
  src/main/java/edu/ucla/library/prl/harvester/Config.java
  src/main/java/edu/ucla/library/prl/harvester/Constants.java
  src/main/java/edu/ucla/library/prl/harvester/OaipmhUtils.java
  src/main/java/edu/ucla/library/prl/harvester/handlers/AbstractRequestHandler.java
  src/main/java/edu/ucla/library/prl/harvester/handlers/AddJobsHandler.java
  src/main/java/edu/ucla/library/prl/harvester/handlers/RemoveJobHandler.java
  src/main/java/edu/ucla/library/prl/harvester/handlers/UpdateJobHandler.java
  src/main/java/edu/ucla/library/prl/harvester/services/HarvestServiceImpl.java
  src/test/java/edu/ucla/library/prl/harvester/OaipmhUtilsFT.java
Labels: feature

#65 [SERV-810] Handle deleted records in ListRecords responses
  src/main/java/edu/ucla/library/prl/harvester/JobResult.java
  src/main/java/edu/ucla/library/prl/harvester/OaipmhUtils.java
  src/main/java/edu/ucla/library/prl/harvester/services/HarvestServiceImpl.java
  src/main/java/edu/ucla/library/prl/harvester/services/HarvestServiceUtils.java
  src/test/java/edu/ucla/library/prl/harvester/JobResultTest.java
  src/test/java/edu/ucla/library/prl/harvester/OaipmhUtilsFT.java
  src/test/java/edu/ucla/library/prl/harvester/services/HarvestJobSchedulerServiceIT.java
  src/test/java/edu/ucla/library/prl/harvester/services/HarvestServiceIT.java
Labels: bugfix

#66 [SERV-802] Don't touch Solr index on no-op job updates
  src/main/frontend/src/components/JobItem.vue
  src/main/java/edu/ucla/library/prl/harvester/Institution.java
  src/main/java/edu/ucla/library/prl/harvester/Job.java
  src/main/java/edu/ucla/library/prl/harvester/handlers/AddJobsHandler.java
  src/main/java/edu/ucla/library/prl/harvester/handlers/RemoveJobHandler.java
  src/main/java/edu/ucla/library/prl/harvester/handlers/UpdateJobHandler.java
  src/main/java/edu/ucla/library/prl/harvester/services/HarvestScheduleStoreServiceImpl.java
  src/main/java/edu/ucla/library/prl/harvester/services/HarvestServiceImpl.java
  src/main/resources/openapi.yaml
  src/test/java/edu/ucla/library/prl/harvester/JobRequestsFT.java
  src/test/java/edu/ucla/library/prl/harvester/JobTest.java
  src/test/java/edu/ucla/library/prl/harvester/OaipmhUtilsFT.java
  src/test/java/edu/ucla/library/prl/harvester/services/HarvestJobSchedulerServiceIT.java
  src/test/java/edu/ucla/library/prl/harvester/services/HarvestScheduleStoreServiceIT.java
  src/test/java/edu/ucla/library/prl/harvester/services/HarvestServiceIT.java
  src/test/java/edu/ucla/library/prl/harvester/utils/TestUtils.java
Labels: bugfix

#69 [SERV-785] Remove Helm references
  .github/workflows/release.yml
  pom.xml
Labels: skip-changelog
