Repository UCLALibrary/prl-harvester, pull requests merged in 2023-04, with the labels that each got.

#52 Display helpful HTTP 400 error messages to admin user
  src/main/frontend/src/components/HarvesterAdmin.vue
  src/main/java/edu/ucla/library/prl/harvester/handlers/InformativeBadRequestHandler.java
  src/main/java/edu/ucla/library/prl/harvester/verticles/MainVerticle.java
  src/main/resources/prl-harvester_messages.xml
  src/test/java/edu/ucla/library/prl/harvester/InstitutionRequestsFT.java
  src/test/java/edu/ucla/library/prl/harvester/JobRequestsFT.java
Labels: enhancement

#53 [SERV-780] Update README with configuration and run instructions
  README.md
Labels: documentation

#56 [SERV-762] Add auth backend
  README.md
  libs/edu/ucla/library/vertx-auth-ldap/4.4.0/vertx-auth-ldap-4.4.0.jar
  libs/edu/ucla/library/vertx-auth-ldap/4.4.0/vertx-auth-ldap-4.4.0.jar.md5
  libs/edu/ucla/library/vertx-auth-ldap/4.4.0/vertx-auth-ldap-4.4.0.jar.sha1
  libs/edu/ucla/library/vertx-auth-ldap/4.4.0/vertx-auth-ldap-4.4.0.pom
  libs/edu/ucla/library/vertx-auth-ldap/4.4.0/vertx-auth-ldap-4.4.0.pom.md5
  libs/edu/ucla/library/vertx-auth-ldap/4.4.0/vertx-auth-ldap-4.4.0.pom.sha1
  libs/edu/ucla/library/vertx-auth-ldap/maven-metadata.xml
  libs/edu/ucla/library/vertx-auth-ldap/maven-metadata.xml.md5
  libs/edu/ucla/library/vertx-auth-ldap/maven-metadata.xml.sha1
  pom.xml
  src/main/docker/Dockerfile
  src/main/docker/configs/logback.xml
  src/main/frontend/src/App.vue
  src/main/java/edu/ucla/library/prl/harvester/Config.java
  src/main/java/edu/ucla/library/prl/harvester/Paths.java
  src/main/java/edu/ucla/library/prl/harvester/handlers/AuthHandler.java
  src/main/java/edu/ucla/library/prl/harvester/verticles/MainVerticle.java
  src/main/resources/prl-harvester_messages.xml
  src/test/java/edu/ucla/library/prl/harvester/AuthorizedFIT.java
  src/test/java/edu/ucla/library/prl/harvester/FrontEndIT.java
  src/test/java/edu/ucla/library/prl/harvester/InstitutionRequestsFT.java
  src/test/java/edu/ucla/library/prl/harvester/JobRequestsFT.java
  src/test/java/edu/ucla/library/prl/harvester/LdapAuthIT.java
  src/test/java/edu/ucla/library/prl/harvester/utils/TestUtils.java
Labels: feature

#57 [SERV-774] Make POST endpoints accept arrays
  src/main/frontend/src/App.vue
  src/main/frontend/src/components/HarvesterAdmin.vue
  src/main/java/edu/ucla/library/prl/harvester/Institution.java
  src/main/java/edu/ucla/library/prl/harvester/Job.java
  src/main/java/edu/ucla/library/prl/harvester/JobResult.java
  src/main/java/edu/ucla/library/prl/harvester/Op.java
  src/main/java/edu/ucla/library/prl/harvester/handlers/AddInstitutionHandler.java
  src/main/java/edu/ucla/library/prl/harvester/handlers/AddInstitutionsHandler.java
  src/main/java/edu/ucla/library/prl/harvester/handlers/AddJobHandler.java
  src/main/java/edu/ucla/library/prl/harvester/handlers/AddJobsHandler.java
  src/main/java/edu/ucla/library/prl/harvester/handlers/RemoveInstitutionHandler.java
  src/main/java/edu/ucla/library/prl/harvester/handlers/RemoveJobHandler.java
  src/main/java/edu/ucla/library/prl/harvester/handlers/ServiceExceptionHandler.java
  src/main/java/edu/ucla/library/prl/harvester/handlers/UpdateInstitutionHandler.java
  src/main/java/edu/ucla/library/prl/harvester/handlers/UpdateJobHandler.java
  src/main/java/edu/ucla/library/prl/harvester/services/HarvestJobSchedulerService.java
  src/main/java/edu/ucla/library/prl/harvester/services/HarvestJobSchedulerServiceImpl.java
  src/main/java/edu/ucla/library/prl/harvester/services/HarvestScheduleStoreService.java
  src/main/java/edu/ucla/library/prl/harvester/services/HarvestScheduleStoreServiceImpl.java
  src/main/java/edu/ucla/library/prl/harvester/services/HarvestServiceUtils.java
  src/main/java/edu/ucla/library/prl/harvester/verticles/MainVerticle.java
  src/main/resources/openapi.yaml
  src/main/resources/prl-harvester_messages.xml
  src/test/java/edu/ucla/library/prl/harvester/InstitutionRequestsFT.java
  src/test/java/edu/ucla/library/prl/harvester/InstitutionTest.java
  src/test/java/edu/ucla/library/prl/harvester/JobRequestsFT.java
  src/test/java/edu/ucla/library/prl/harvester/JobResultTest.java
  src/test/java/edu/ucla/library/prl/harvester/JobTest.java
  src/test/java/edu/ucla/library/prl/harvester/services/HarvestJobSchedulerServiceIT.java
  src/test/java/edu/ucla/library/prl/harvester/services/HarvestScheduleStoreServiceIT.java
  src/test/java/edu/ucla/library/prl/harvester/services/HarvestServiceIT.java
  src/test/java/edu/ucla/library/prl/harvester/utils/TestUtils.java
Labels: breaking

#58 [SERV-796] Trust image filename extensions of URLs
  src/main/java/edu/ucla/library/prl/harvester/services/HarvestServiceUtils.java
  src/test/java/edu/ucla/library/prl/harvester/services/HarvestServiceUtilsTest.java
Labels: enhancement
